FROM node:20-alpine

RUN apk add --no-cache \
    python3 \
    g++ \
    make \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev \
    pixman-dev \
    cairo \
    jpeg \
    pango \
    giflib \
    pixman \
    fontconfig \
    ttf-dejavu \
    curl

WORKDIR /app

RUN mkdir -p logs && \
    chmod 777 logs

COPY package*.json ./

RUN npm install

EXPOSE 2000 9229

ENV NODE_ENV=development
ENV DEBUG_MODE=true

CMD ["npm", "run", "dev"]