version: '3.9'

# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    command: npm run dev

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  # Development tools
  adminer:
    profiles: []  # Always enabled in dev
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: ${POSTGRES_DB:-pegasus}

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pegasus-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD:-changeme}
    ports:
      - "8081:8081"
    networks:
      - pegasus-network
    depends_on:
      - redis

volumes:
  node_modules:
    driver: local